apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-classes
  namespace: argocd
  # The finalizer ensures a cascading delete (removes managed K8s resources when the app is deleted)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The Argo CD Project the application belongs to (default is built-in)
  project: default

# Source definition: Where your Kubernetes manifests live
  source:
    repoURL: 'https://github.com/VasarlaSravanthi/argocd.git'
    targetRevision: main      # Can be a branch (main), a tag (v1.0.0), or a commit SHA
    path: storage-classes           # The subfolder containing your YAML manifests or Helm charts

  # Destination definition: Where the application will be deployed
  destination:
    server: 'https://kubernetes.default.svc' # Points to the local cluster Argo CD is installed on
    namespace: default  

 # Synchronization policy configuration
  syncPolicy:
    automated:
      prune: true     # Automatically deletes resources from cluster if removed from Git
      selfHeal: true  # Automatically fixes drift if cluster configuration is changed manually
 